version: '3.9'

services:
    nginx:
        build: requirements/nginx
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        restart: always
        volumes: 
            - ./inception/wordpress:/etc/setup/wordpress
        ports:
            - "443:443"
        networks:
            - inception
        env_file: 
            - ".env"
    mariadb:
        build: requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: always
        volumes: 
            - ./inception/mysql:/var/lib/mysql
            - ./inception/cgroup:/sys/fs/cgroup
        networks:
          - inception
        env_file: 
            - ".env"
    wordpress:
        build: requirements/wordpress
        image: wordpress
        container_name: wordpress
        depends_on:
            - mariadb
        volumes: 
            - ./inception/wordpress:/etc/setup/wordpress
        restart: always
        networks:
            - inception
        env_file: 
            - ".env"
    ftps:
        build: requirements/bonus/ftps
        image: ftps
        container_name: ftps
        depends_on:
            - wordpress
        restart: always
        networks:
            - inception
        volumes: 
            - ./inception/wordpress:/home/msnazarow/wordpress
        env_file: 
            - ".env"
        ports:
            - ${FTPPORT}:${FTPPORT}
            - "21:21"
            - "22:22"
    adminer:
        build: requirements/bonus/adminer
        image: adminer
        container_name: adminer
        networks:
            - inception
        restart: always
        ports:
          - 8080:8080
        env_file:
            - ".env"
    grafana:
        build: requirements/bonus/grafana
        depends_on: 
            - influxdb
        image: grafana
        container_name: grafana
        networks:
            - inception
        restart: always
        ports:
          - 3000:3000
        env_file:
            - ".env"
    influxdb:
        build: requirements/bonus/influxdb
        image: influxdb
        container_name: influxdb
        networks:
            - inception
        volumes: 
            - ./inception/influxdb:/root/.influxdb/
            - /var/run/docker.sock:/var/run/docker.sock 
        restart: always
        env_file:
            - ".env"
    mycoolsite:
        build: requirements/bonus/mycoolsite
        image: mycoolsite
        container_name: mycoolsite
        networks: 
            - "inception"
        restart: always
        ports: 
            - "5050:5050"
networks:
    inception:
        name: "inception"